apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80          # External port exposed by the Service
      targetPort: 8080  # Internal port where the application is running
  selector:
    app: spring-boot-app
